### ISSUE TITLE
[Bug]: Draw condition

### ISSUE THREAD

**Issue by aobakwewastaken** [scriptjumper/Tic-Tac-Toe#1]
## Bug Report

**Current Behavior**
When the game reaches a stalemate it does not flag that

**Comment by scriptjumper** [comment]
@OkayAobakwe do you have a possible fix for this ?

**Comment by aobakwewastaken** [comment]
When there are no moves available and neither x or o has won that should be flagged as a draw, and users should be prompted to restart the game @scriptjumper
